name: IHome
main: infomcpe\IHome
author: Алексей
version: 1.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
load: STARTUP
website: infomcpe.ru
commands:
    ihome:
        description: "Телепорт домой"
        aliases: [ih] 
    sethome:
        description: Установить точку дома
        default: true
    delhome:
        description: Удалить точку дома
        default: true
    home:
        description: Телепортирываться домой
        default: true
    setprivate:
        description: Установить дом как приватный
        default: true
    setpublic:
        description: Установить дом как публичный
        default: true

